# Generated by Django 5.0.1 on 2024-02-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_razon_social_maritimas_maritima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='precios',
            name='ruta',
            field=models.CharField(max_length=80),
        ),
    ]
