# Generated by Django 5.0.2 on 2024-02-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_rutas_codigo_alter_precios_ruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='maritimas',
            options={'verbose_name': 'Maritima', 'verbose_name_plural': 'Maritimas'},
        ),
        migrations.AlterModelOptions(
            name='precios',
            options={'verbose_name': 'Precio', 'verbose_name_plural': 'Precios'},
        ),
        migrations.AlterModelOptions(
            name='rutas',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
    ]
